apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-service
  namespace: venus
  labels:
    app: doctor-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: doctor-service
  template:
    metadata:
      labels:
        app: doctor-service
        tier: backend
    spec:
      containers:
        - name: doctor-service
          image: 292681319373.dkr.ecr.us-east-1.amazonaws.com/venus-doctor-service:ba579c30323c2cc88c7d71f90d4694b77a324b87
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: venus-config
          env:
            - name: DB_NAME
              value: "venus_doctor_db"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: doctor-service
  namespace: venus
  labels:
    app: doctor-service
spec:
  type: ClusterIP
  selector:
    app: doctor-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
