apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: venus-base
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vijaykumarbvk/venus-hospital-python-ui.git
    path: k8s-base
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: venus
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
