apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: venus-appointment-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vijaykumarbvk/venus-hospital-python-ui.git
    path: services/appointment_service
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: venus
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
